apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-app
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/PROJECT_ID/my-repo/my-app:REPLACE_IMAGE_TAG
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: "staging"
