apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: my-app
build:
  artifacts:
    - image: europe-west1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app
deploy:
  kubectl:
    manifests:
      - app.yaml
