apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: my-app
build:
  artifacts:
    - image: europe-west1-docker.pkg.dev/hsrm-cloud-1/my-repo/my-app
manifests:
  rawYaml:
    - app.yaml
deploy:
  cloudrun:
    projectid: hsrm-cloud-1
    region: europe-west1
