apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: "Staging environment"
run:
  location: projects/hsrm-cloud-1/locations/europe-west1
executionConfigs:
  - usages: [RENDER, DEPLOY]
    defaultPool:
      serviceAccount: cloud-deploy-sa@hsrm-cloud-1.iam.gserviceaccount.com